# Service for the admission app
apiVersion: v1
kind: Service
metadata:
  name: admission-service
spec:
  selector:
    app: admission-checker
  ports:
  - port: 8080
    targetPort: 8080
  type: ClusterIP